zoom:
  client_id: thisisclientid
  client_secret: thisisclientsecret
  account_id: thisisaccountid

drive:
  credentials: credentials.json
  folder_name: z2gd

client:
  fetch_api: false
  download_location: /tmp
  db_location: file:./data.db
  file_type: MP4
  record_type: []
  cutoff: 1685846792
  dry_run: true
  retry: 0
  user_ids: []
